# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b7da85aa0beb16723f617e1af56b970f967d4e66ccd552516543b9224efe5b54b9fc59f34e33d4b09ebb345b87183fd17c4d6ed31fe93e976e25c6161668dfb

test:
  secret_key_base: 4062a617259282df5163214d194852f792550ca214d06688e1558f11ab6d41cc184e17385354ba98bf0af40f77c4f0b92e3cce7905f11256e65994f6f9538924

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
